services:
    # Session handler for production (Heroku) - Use Doctrine DBAL connection
    # This service is only loaded in production environment
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - !service { class: PDO, factory: ['@doctrine.dbal.default_connection', 'getNativeConnection'] }
            -
                db_table: 'sessions'
                db_id_col: 'sess_id'
                db_data_col: 'sess_data'
                db_time_col: 'sess_time'
                db_lifetime_col: 'sess_lifetime'
